Improve data v1
etalab/siade_staging_data pull request #29
Opened 2023-05-26 09:30 UTC by Haelle

J'ai ajouté la contrainte de systématiquement devoir ajouter une description.

Le but ici étant de nous forcer à décrire le cas d'usage de tel ou tel cas de test et dire en quelques mots pourquoi il est différent des autres

2023-05-26 12:16 UTC, Samuelfaure commented on lib/open_api_schema_to_example.rb
> +      sub_schema['nullable'] ? nil : 'dummy'
Du coup y'a un intérêt à mettre nil plutôt que dummy sur un champs nullable?

Si tu le fait pour un string faut ptêtre le faire aussi sur integer et booleen?

2023-05-26 14:19 UTC, Haelle commented on lib/open_api_schema_to_example.rb
> +      sub_schema['nullable'] ? nil : 'dummy'
Je l'avais mis à cause de ça `telephone2` : https://github.com/etalab/siade/blob/40197279d6d4abcd8ef93d30030defe887a9206b/swagger/openapi-particulier.yaml#L790-L794
Et de ça `dateFin` : https://github.com/etalab/siade/blob/40197279d6d4abcd8ef93d30030defe887a9206b/swagger/openapi-particulier.yaml#L1830-L1839

Ce sont des champs nullables, et on renvoie par défaut `example` ce qui... n'est ni une date valide (format date) ni un numéro de téléphone valide (là je sais plus pourquoi ça buggait vu qu'il n'y a pas de regex).

Du coup j'ai viré cette ligne au profit d'`example` dans le Swagger

2023-05-29 08:57 UTC, skelz0r requested changes
cf mes coms

2023-05-29 08:57 UTC, skelz0r commented on bin/bootstrap_payload.rb
> +  end
```suggestion
end
```

a revert

2023-05-29 08:57 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +    raise("All response must have a description (#{payload_path})") if payload['description'].blank?
Un poil violent, j'aurais plutôt utilisé les tests ici pour vérifier que c'est bien présent.

2023-05-29 08:57 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +    readme_stream.puts "lors d'un appel avec des paramètres valides l'API renvoie systématiquement cette réponse :"
```suggestion
    readme_stream.puts "Lors d'un appel avec des paramètres valides ne correspondant à aucun des examples dans ce dossier, l'API renvoie systématiquement cette réponse :"
```

2023-05-29 08:57 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +  def add_default_payload_infos
Le formatage ne me semble pas adapté (cf les readme plus bas(, à fixer.

2023-05-30 07:54 UTC, Haelle commented on lib/generate_payload_readme.rb
> +    raise("All response must have a description (#{payload_path})") if payload['description'].blank?
Oui on peut utiliser des tests en effet, mais il faut s'assurer qu'on en ait partout. Ça incite à penser "cas d'usage", que chaque cas ait une raison d'exister au vu des autres cas.

2023-05-30 08:00 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +    raise("All response must have a description (#{payload_path})") if payload['description'].blank?
Avec ta réflexion il faudrait aussi vérifier que les params sont là, que la payload est là, qu'elle est valide etc etc.. c'est exactement le rôle des tests.

2023-05-30 08:45 UTC, Haelle commented on lib/generate_payload_readme.rb
> +  def add_default_payload_infos
C'est à dire ? Mettre un block params/response/cURL ?

2023-05-30 08:50 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +  def add_default_payload_infos
je pense que ça va juste être dégueu sur le rendu vu comment c'est indenté.

2023-05-30 09:05 UTC, Haelle commented on lib/generate_payload_readme.rb
> +  def add_default_payload_infos
en effet j'ai zappé de regarder le rendu... j'ai juste checké le markdown...
Fixed (wdyt ?) : 
![image](https://github.com/etalab/siade_staging_data/assets/5159985/8177285a-6deb-4605-8b8a-469b6d0665e9)

2023-05-30 09:34 UTC, skelz0r commented on lib/generate_payload_readme.rb
> +  def add_default_payload_infos
Très bien !

2023-05-30 13:54 UTC, merged