Added INSEE Liens de Succession
etalab/siade_staging_data pull request #75
Opened 2024-04-29 01:06 UTC by Samuelfaure

fix https://linear.app/pole-api/issue/API-2714/conception-des-cas-de-tests-%F0%9F%A7%AA

2024-04-29 09:04 UTC, Un3x requested changes
Cf commentaire.
En vrai j'suis pas sûr que ce soit fondamental mais restons iso.

2024-04-29 09:04 UTC, Un3x commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Il manque peut être un title et une payload ?

2024-04-29 09:04 UTC, Un3x commented on payloads/api_entreprise_v3_insee_successions/403.yaml
> +params:
idem

2024-05-01 06:13 UTC, Samuelfaure commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Effectivement il manque un titre ! Mais il y a bien une payload?...

2024-05-02 08:31 UTC, Un3x commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
oui je suppose que ca fonctionne quand même.

2024-05-03 03:00 UTC, Samuelfaure commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Je comprend pas cette discussion 😅

Tu dis qu'il manque un titre et une payload, il manque le titre mais il y a bien une payload?

(Sidenote, je fait un ticket pour rendre les titres obligatoires dans les tests)

2024-05-03 08:19 UTC, skelz0r commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Je pense qu'il parle de description.

2024-05-03 08:21 UTC, skelz0r commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Et oui par contre si le titre est obligatoire (?) faut ajouter ça dans les tests.

2024-05-03 08:33 UTC, Samuelfaure commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
Y'a une description déjà puiqu'elle est obligatoire dans les tests

2024-05-03 08:36 UTC, skelz0r commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
en effet

2024-05-03 08:37 UTC, Samuelfaure commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
175 payloads n'ont pas de titre cela dit, je me fais chier à en rajouter un à votre avis ou osef? @Un3x @skelz0r

2024-05-03 08:41 UTC, skelz0r commented on payloads/api_entreprise_v3_insee_successions/200.yaml
> +params:
🤷

imo à discuter dans une autre issue (et voir à quoi ça sert aussi)

2024-05-23 05:02 UTC, merged